[package]
name = "plant-evolution"
version = "0.1.0"
edition = "2024"

[lib]
name = "plant_evolution_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "plant_evolution_app"
path = "src/app/main.rs"

[dependencies]
eframe = "0.34.2"
egui = "0.34.2"
rand = "0.10.1"
winit = "0.30.13"
hotpath = "0.21.2"
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.45"

[features]
stable_rng = []
hotpath = ["hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[profile.bench]
debug = true

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "growth"
harness = false
features = ["stable_rng"]

[[bench]]
name = "evolution"
harness = false
features = ["stable_rng"]
