[package]
name = "plant-evolution"
version = "0.1.0"
edition = "2024"

[lib]
name = "plant_evolution_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "plant_evolution_app"
path = "src/app/main.rs"

[dependencies]
eframe = "0.36.1"
egui = "0.36.1"
rand = "0.10.2"
winit = "0.30.13"
hotpath = "0.23.3"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
chrono = "0.4.45"
scoped_threadpool = { version = "0.1.9", optional = true }
directories-next = "2.0.0"
egui_plot = "0.37.0"
meval = { version = "0.2.0", optional = true }
tabulon = { version = "0.1.10", optional = true }
mathexpr = { version = "0.1.1", optional = true }

[features]
default = ["thread_evolution", "meval_formula", "tabulon_formula", "mathexpr_formula"]
stable_rng = []
thread_evolution = ["dep:scoped_threadpool"]
hotpath = ["hotpath/hotpath", "stable_rng"]
hotpath-cpu = ["hotpath/hotpath-cpu", "stable_rng"]
hotpath-alloc = ["hotpath/hotpath-alloc", "stable_rng"]

meval_formula = ["dep:meval"]
tabulon_formula = ["dep:tabulon"]
mathexpr_formula = ["dep:mathexpr"]

[profile.bench]
debug = true

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
cranelift-jit = "0.134.3"
meval = "0.2.0"
tabulon = "0.1.10"
evalexpr-jit = "0.2.3"
approx = "0.5.1"

[dev-dependencies.plant-evolution]
path = "."
features = ["stable_rng"]

[[bench]]
name = "growth"
harness = false
required-features = ["stable_rng"]

[[bench]]
name = "evolution"
harness = false
required-features = ["stable_rng"]

[[bench]]
name = "full"
harness = false
required-features = ["stable_rng"]

[[bench]]
name = "formula"
harness = false
